version: "3.7"
services:
  db:
    image: mysql:5.7
    container_name: mysql-albadon
    ports:
      - "3307:3306"
    environment:
      - MYSQL_DATABASE=albadon
      - MYSQL_ROOT_PASSWORD=password
      - TZ=Asia/Seoul

    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    volumes:
      - ./data:/var/lib/mysql
      - ./init/:/docker-entrypoint-initdb.d
