server:
  tomcat:
    basedir: ./
    accesslog:
      enabled: true
      buffered: true
      #directory: logs/
      rotate: true
      prefix: access_
      pattern: combined
      suffix: ".log"
      fileDateFormat: "yyyy-MM-dd"
  port: 8080

spring:
  application:
    name: "albadon-api"
  jpa:
    open-in-view: true
    generate-ddl: false
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate.dialect: org.hibernate.dialect.MySQL57InnoDBDialect
      hibernate.format_sql: true
      hibernate.enable_lazy_load_no_trans: true
      hibernate.connection.handling_mode: DELAYED_ACQUISITION_AND_RELEASE_AFTER_TRANSACTION
      hibernate.physical_naming_strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
      hibernate.implicit_naming_strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy
  datasource:
    url: jdbc:mysql://192.168.0.2:3306/albadon?useSSL=false&characterEncoding=UTF-8&serverTimezone=Asia/Seoul
    username: root
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver